studio/webapp/alpr/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


from . import views

app_name='alpr'

urlpatterns = [
    path('playback', views.playback, name='playback'),
    path('webcam', views.webcam, name='webcam'),
    path('upload', views.upload, name='upload'),
    path('remove', views.remove, name='remove'),

    path('play', views.play, name='play'),
    path('stop', views.stop, name='stop'),
    path('get_vehicle', views.get_vehicle, name='get_vehicle'),
    path('remove_vehicle_history', views.remove_vehicle_history, name='remove_vehicle_history'),
    path('get_captured_plate', views.get_captured_plate, name='get_captured_plate'),
    path('get_captured_vehicle', views.get_captured_vehicle, name='get_captured_vehicle'),

    path('config', views.config, name='config'),
    
    path('', views.index, name='index'),
]

if settings: 
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root = settings.MEDIA_ROOT) 

studio/webapp/login/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login/login.html'), name='login'),
    path('', auth_views.LoginView.as_view(template_name='login/login.html'), name='login_root'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
	path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
	path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

studio/webapp/webapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('alpr/', include('alpr.urls')),
    path('login/', include('login.urls')),
    path('', include('login.urls')),
    path('duo/', include('duo_universal_auth.urls')),
	path('accounts/', include('login.urls')),
]

studio/webapp/templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'alpr:index' %}">ALPR SYSTEM</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'login:logout' %}">{{ user.username }} (Logout)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'login:login' %}">Login</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'login:password_reset' %}">Lost Password</a>
                    {% endif %}
                </li>
                <li>
                    {% if user.is_superuser %}
                    <a class="nav-link" href="{% url 'login:signup' %}">New Account</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>